[build]
builder = "nixpacks"
buildCommand = "curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs && cd frontend && npm install && npm install --save-dev @types/node && npm run build"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && gunicorn src.app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 