[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm install --save-dev @types/node && npm run build && cp -r dist/frontend/* ../backend/static/"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && gunicorn src.app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 