[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm install --save-dev @types/node && npm run build && mkdir -p ../backend/static && cp -r dist/* ../backend/static/ || echo 'Copy failed, checking directories:' && ls -la frontend/dist/ || echo 'dist not found'"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && gunicorn src.app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3 